### ISSUE TITLE
Nodes in wrong namespace

### ISSUE THREAD

**Issue by Twoshrubs** [markusgraube/opc_ua_xml_export_client#2]
Hello,

We have 3 namespaces on our server.

0 = standard OPC UA
1 = created by Open62451 logic
2 = Our custom namespace

When looking at the server using a client all our model is in nodespace 2 but when we do an export about 99% of nodespace 2 nodes in the model and objects export out as nodespace 1

If you like any more information please let me know.

**Comment by markusgraube** [comment]
Hi @Twoshrubs,

currently I can't reproduce your problem.
Can you provide the output of the command and perhaps also the generated XML?
Have you tried only to export one namespace be providing e.g. `-n 2`
